version: 1.2
workflows:
  - subclass: CW:
    primaryDescriptorPath: /Dockstore.cwl
    testParameterFiles:
        - /test.json
   - subclass: WDL
     primaryDescriptorPath: /Dockstore.wdl
     testParameterFiles:
         - /test.wdl.json
