name: Test workflows

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        push: false
        tags: quay.io/collaboratory/dockstore-tool-bamstats
    - name: Setup Python
      run: bash before-install.sh
    - name: Setup engines
      run: bash install.sh
    - name: Run workflows
      run: bash script.sh
